package com.mewcode.provider;

/**
 * Callback invoked for each streamed chunk from an LLM provider.
 */
public interface StreamCallback {

    /**
     * Called when a new chunk of text arrives from the model.
     *
     * @param text the delta text (may be empty string, never null)
     * @param type what kind of chunk this is
     */
    void onChunk(String text, ChunkType type);

    /**
     * Called when the stream has finished normally.
     *
     * @param stopReason the reason the model stopped (e.g. "end_turn", "tool_use", "max_tokens")
     */
    default void onComplete(String stopReason) {}

    /**
     * Called after the stream ends with aggregate token usage.
     *
     * @param inputTokens        total input tokens consumed by this request
     * @param outputTokens       total output tokens generated by this request
     * @param cacheCreationTokens tokens written into the prompt cache (0 if none)
     * @param cacheReadTokens    tokens read from a pre-existing cache entry (0 if none)
     */
    default void onUsage(int inputTokens, int outputTokens,
                         long cacheCreationTokens, long cacheReadTokens) {}

    /**
     * Called when an error occurs during streaming.
     */
    default void onError(Throwable t) {
        System.err.println("\n[错误] " + t.getMessage());
    }
}
